/** @type {import('tailwindcss').Config} */
export default {
    theme: {
        extend: {
            colors: {
                // Paleta inspiradora
                'coral': {
                    50: '#fff5f5',
                    100: '#ffe0df',
                    200: '#ffc2c0',
                    300: '#ff9d99',
                    400: '#ff8787',
                    500: '#FF6B6B',
                    600: '#ff5252',
                    700: '#e63946',
                    800: '#cc3333',
                    900: '#991f1f',
                },
                'mint': {
                    50: '#f0fdf4',
                    100: '#dcfce7',
                    200: '#bbf7d0',
                    300: '#86efac',
                    400: '#48BB78',
                    500: '#16a34a',
                    600: '#15803d',
                    700: '#166534',
                    800: '#14532d',
                    900: '#0d3a1f',
                },
                'gold': {
                    50: '#fffbf0',
                    100: '#fef3c7',
                    200: '#fde68a',
                    300: '#fcd34d',
                    400: '#fbbf24',
                    500: '#FFD166',
                    600: '#f59e0b',
                    700: '#d97706',
                    800: '#b45309',
                    900: '#78350f',
                },
            },
            fontFamily: {
                'sans': ['Instrument Sans', 'ui-sans-serif', 'system-ui', 'sans-serif'],
                'display': ['Instrument Sans', 'ui-sans-serif', 'system-ui', 'sans-serif'],
            },
            fontSize: {
                'xs': ['0.75rem', { lineHeight: '1.5rem' }],
                'sm': ['0.875rem', { lineHeight: '1.5rem' }],
                'base': ['1rem', { lineHeight: '1.75rem' }],
                'lg': ['1.125rem', { lineHeight: '1.75rem' }],
                'xl': ['1.25rem', { lineHeight: '1.75rem' }],
                '2xl': ['1.5rem', { lineHeight: '2rem' }],
                '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
                '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
                '5xl': ['3rem', { lineHeight: '3.5rem' }],
            },
            fontWeight: {
                'thin': '100',
                'extralight': '200',
                'light': '300',
                'normal': '400',
                'medium': '500',
                'semibold': '600',
                'bold': '700',
                'extrabold': '800',
                'black': '900',
            },
            animation: {
                'pulse-glow': 'pulse-glow 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
                'shimmer': 'shimmer 2s infinite',
                'float': 'float 3s ease-in-out infinite',
                'slide-up': 'slide-up 0.5s ease-out',
                'slide-down': 'slide-down 0.3s ease-out',
                'fade-in': 'fade-in 0.5s ease-out',
                'scale-in': 'scale-in 0.3s ease-out',
                'counter': 'counter 2s ease-out forwards',
            },
            keyframes: {
                'pulse-glow': {
                    '0%, 100%': { opacity: '1' },
                    '50%': { opacity: '0.5' },
                },
                'shimmer': {
                    '0%': { backgroundPosition: '-1000px 0' },
                    '100%': { backgroundPosition: '1000px 0' },
                },
                'float': {
                    '0%, 100%': { transform: 'translateY(0px)' },
                    '50%': { transform: 'translateY(-20px)' },
                },
                'slide-up': {
                    'from': { transform: 'translateY(20px)', opacity: '0' },
                    'to': { transform: 'translateY(0)', opacity: '1' },
                },
                'slide-down': {
                    'from': { transform: 'translateY(-10px)', opacity: '0' },
                    'to': { transform: 'translateY(0)', opacity: '1' },
                },
                'fade-in': {
                    'from': { opacity: '0' },
                    'to': { opacity: '1' },
                },
                'scale-in': {
                    'from': { transform: 'scale(0.95)', opacity: '0' },
                    'to': { transform: 'scale(1)', opacity: '1' },
                },
                'counter': {
                    'from': { content: '0' },
                    'to': { content: '100' },
                },
            },
            backdropBlur: {
                'xl': '20px',
                '2xl': '40px',
            },
            spacing: {
                '18': '4.5rem',
                '20': '5rem',
                '24': '6rem',
                '28': '7rem',
                '32': '8rem',
            },
            borderRadius: {
                'none': '0',
                'sm': '0.375rem',
                'base': '0.5rem',
                'md': '0.75rem',
                'lg': '1rem',
                'xl': '1.25rem',
                '2xl': '1.5rem',
                '3xl': '2rem',
                'full': '9999px',
            },
            boxShadow: {
                'glass': '0 8px 32px 0 rgba(31, 38, 135, 0.15)',
                'glass-lg': '0 8px 32px 0 rgba(31, 38, 135, 0.25)',
                'soft': '0 5px 15px rgba(0, 0, 0, 0.1)',
                'soft-lg': '0 10px 30px rgba(0, 0, 0, 0.15)',
                'warm': '0 8px 24px rgba(255, 107, 107, 0.15)',
                'hover': '0 12px 40px rgba(0, 0, 0, 0.2)',
            },
        },
    },
    plugins: [],
};
